### ISSUE TITLE
Could not find com.github.kishandonga:EasyPrefs:1.1.

### ISSUE THREAD

**Issue by houmie** [kishandonga/EasyPrefs#2]
Sorry I'm new to Android development.

In the build.gradle(Project) I have added this:
```
repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
```

In the build.gradle(App) I added this:
```
dependencies {
  ...
    implementation 'com.github.kishandonga:EasyPrefs:1.1'
}
```

When I rebuild the project I get this:

**Could not find com.github.kishandonga:EasyPrefs:1.1.
Required by:
    project :app**

Isn't this like CocoaPods in iOS where the libs get pulled automatically? Do I still have to copy and paste the lib by hand into my project? Is there a better way? Thanks

**Comment by kishandonga** [comment]
Please change your Gradle configuration as like, because I check twice it is working if you still face any issue then let me know.

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```

```
dependencies {
  ...
    implementation 'com.github.kishandonga:EasyPrefs:1.1'
}
```

**Comment by kishandonga** [comment]
I think now your issue resolved.
